version: '3'
services:
  cassandra:
    image: cassandra:3.11
    ports:
      - "9042:9042"
      - "9160:9160"
    environment:
      CASSANDRA_DC: local-dc # The 'region' where Cassandra is deployed.
      CASSANDRA_RACK: local-rack # THe 'rack' where Cassandra is deployed. 
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch # Location awareness.
  service:
    image: node:8
    working_dir: /app
    command: "npm run startdev"
    ports:
      - "3000:3000"
    environment:
      CASSANDRA_HOST: cassandra:9042 # Cassandra instance defined above
      CASSANDRA_KEYSPACE: test_table # {Change to match application's keyspace.}
      CASSANDRA_REGION: local-dc # Matches CASSANDRA_DC
    volumes: 
      - ./back-end/:/app
    depends_on:
      - cassandra
networks:
  service:
    driver: "bridge"